language: node_js
node_js:
- '10'
branchs:
  only:
  - master
install:
- rm -f package-lock.json && cnpm install 
script:
- cnpm run build
before_install:
- openssl aes-256-cbc -K $encrypted_1db7356b8c0c_key -iv $encrypted_1db7356b8c0c_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
    -git pull
